[package]
name = "enreco"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.2.4"
steamworks = "0.11.x"

[dependencies.enreco_derive]
version = "0.1.x"
path = "../enreco_derive"
